grpc:
  client:
    converterClient:
      address: ${CONVERTER_URL:localhost:56977}
      keepAliveWithoutCalls: true
      negotiation-type: PLAINTEXT

spring:
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:accounts}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by.default_null_ordering: last
        format_sql: true
        default_schema: public
    open-in-view: false
    show-sql: false
    generate-ddl: true

  main:
    web-application-type: servlet

logging:
  level:
    root: info

management:
  endpoint:
    health:
      probes:
        enabled: true

bucket4j:
  enabled: true
  methods:
    - name: default
      cache-name: buckets
      rate-limit:
        bandwidths:
          - capacity: 5
            refill-capacity: 5
            time: 1
            unit: minutes
            initial-capacity: 5
            refill-speed: interval

resilience4j:
  circuitbreaker:
    configs:
      default:
        wait-duration-in-open-state:
          seconds: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      converterService:
        base-config: default
