rates-service:
  url: ${RATES_URL:http://localhost:51128}
  rates-path: ${rates-service.url}/rates

grpc:
  server:
    port: 9090

spring:
  security:
    oauth2:
      client:
        registration:
          converter:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: basic
            provider: keycloak
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_URL:http://localhost:63608}/realms/${KEYCLOAK_REALM:hse}/protocol/openid-connect/token

logging:
  level:
    root: info

management:
  endpoint:
    health:
      probes:
        enabled: true
