name: build-workflow
run-name: ${{ github.actor }} ${{ github.event_name }}
on:
  push:
    branches: [ "main", "refactor" ]
  pull_request:
    branches: [ "main" ]

env:
  docker-tag: ${{ github.head_ref || github.ref_name }}-${GITHUB_SHA::7}

jobs:
  autotest:
    needs: [build]
    if: github.event_name == 'pull_request'
    uses: ./autotests-hw9-logs.yml@main
    with:
      chart-path: ./mychart
      converter-image-name: orobtsovv/converter
      accounts-image-name: orobtsovv/accounts
      image-tag: ${{ needs.build.outputs.docker-tag }}
    secrets:
      HSE_LOKI_TOKEN: ${{ secrets.HSE_LOKI_TOKEN }}

  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven clean install
        run: mvn clean install

      - name: Build Docker converter image
        run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/converter:${{ env.docker-tag }} ./converter
      - name: Build Docker accounts image
        run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/accounts:${{ env.docker-tag }} ./accounts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the converter image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/converter:${{ env.docker-tag }}
      - name: Push the accounts image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/accounts:${{ env.docker-tag }}

      - name: Tag Docker converter image as latest
        run: |
          docker image tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/converter:${{ env.docker-tag }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/converter:latest
        if: github.ref == 'refs/heads/main'

      - name: Push latest converter image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/converter:latest
        if: github.ref == 'refs/heads/main'

      - name: Tag Docker accounts image as latest
        run: |
          docker image tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/accounts:${{ env.docker-tag }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/accounts:latest
        if: github.ref == 'refs/heads/main'

      - name: Push latest accounts image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/accounts:latest
        if: github.ref == 'refs/heads/main'

    outputs:
      docker-tag: ${{ env.docker-tag }}
