name: build-workflow
run-name: ${{ github.actor }} ${{ github.event_name }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  docker-tag: ${{ github.head_ref || github.ref_name }}-${GITHUB_SHA::7}

jobs:
  autotest:
    needs: build
    uses: central-university-dev/hse-ab-cicd-hw/.github/workflows/autotests.yml@main
    with:
      chart-path: ./mychart 
      image-name: orobtsovv/demo-image 
      image-tag: ${{ needs.build.outputs.docker-tag }} 
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven clean install
        run: mvn clean install

      - name: Build Docker image
        run: docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/demo-image:${{ env.docker-tag }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-image:${{ env.docker-tag }}

      - name: Tag Docker image as latest
        run: |
          docker image tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/demo-image:${{ env.docker-tag }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/demo-image:latest
        if: github.ref == 'refs/heads/main'
      - name: Push latest image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-image:latest
        if: github.ref == 'refs/heads/main'

    outputs:
      docker-tag: ${{ env.MAVEN_VERSION }}
